#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import subprocess
import sys

import numpy

import common


def _main(*args):
    parser = argparse.ArgumentParser(
        description='Convert a processed image to Y4M video. The output is written to stdout.')
    parser.add_argument('input_files', type=str, nargs='+',
                        help='Input file(s). Should be TIFF images generated by generate.sh or equivalent. Will be passed to ImageMagick.')
    parser.add_argument('--framerate', type=float,
                        help='Output framerate. 25 by default, except if the input is 480 or 486 lines, then 29.97.')
    parser.add_argument('--aspect169', action='store_true',
                        help='Use 16:9 aspect ratio for SD video (or 5:4 for 405-line, yes, it\'s a hack).')
    parser.add_argument('--loop', type=int, default=1,
                        help='Repeat the frames the specified number of times.')
    args = parser.parse_args(args)

    frames = []
    for filename in args.input_files:
        width, height = subprocess.run(['magick', 'identify', '-format', '%wx%h', filename],
                                       stdout=subprocess.PIPE, check=True).stdout.decode().split(
            'x')
        width = int(width)
        height = int(height)
        if len(frames) > 0:
            if width != frames[0].shape[1] or height != frames[0].shape[0]:
                raise Exception('Inconsistent frame size')

        data = subprocess.run(
            ['magick', filename, '-define', 'quantum:format=floating-point', '-depth', '64',
             'rgb:-'], stdout=subprocess.PIPE, check=True).stdout
        assert len(data) == width * height * 3 * 8
        data = numpy.ndarray((height, width, 3), dtype=numpy.float64, buffer=data).copy()
        frames.append(data)

    frames = numpy.stack(frames).transpose((0, 3, 1, 2))

    if frames.shape[1] >= 720:
        colorspace = common.ColorSpace.BT709
    else:
        colorspace = common.ColorSpace.BT601
    frames = numpy.matvec(colorspace.from_rgb_matrix, frames, axes=[(0, 1), 1, 1])
    frames[:, 0, :, :] = 3504 * frames[:, 0, :, :] + 256
    frames[:, 1:, :, :] = 3584 * frames[:, 1:, :, :] + 2048
    frames = numpy.array(numpy.round(numpy.minimum(numpy.maximum(frames, 0), 4095)),
                         dtype=numpy.uint16)

    header = f'YUV4MPEG2 W{frames.shape[3]} H{frames.shape[2]}'

    if args.framerate is None:
        if 480 <= frames.shape[2] <= 486:
            header += ' F30000:1001'
        else:
            header += ' F25:1'
    elif abs(float(args.framerate) - round(float(args.framerate))) < 0.01:
        header += f' F{int(round(float(args.framerate)))}:1'
    else:
        header += f' F{int(round(float(args.framerate) * 1001))}:1001'

    if frames.shape[2] <= 486:
        header += ' Ib'
    elif frames.shape[2] <= 576:
        header += ' It'
    else:
        header += ' Ip'

    if 480 <= frames.shape[2] <= 486:
        if args.aspect169:
            header += ' A32:27'
        else:
            header += ' A8:9'
    elif frames.shape[2] == 576:
        if args.aspect169:
            header += ' A64:45'
        else:
            header += ' A16:15'
    elif frames.shape[2] == 378:
        if args.aspect169:
            header += ' A21:32'
        else:
            header += ' A7:10'
    else:
        header += ' A1:1'

    header += ' C444p12 XYSCSS=444P12 XCOLORRANGE=LIMITED'
    header += '\n'

    buffer = bytearray(numpy.prod(frames[0].shape) * 2)
    output = numpy.ndarray(frames[0].shape, dtype=numpy.uint16, buffer=buffer)
    with open('/dev/stdout', 'wb') as f:
        f.write(header.encode())
        for loop in range(args.loop):
            for i in range(frames.shape[0]):
                f.write(b'FRAME\n')
                output[...] = frames[i]
                f.write(buffer)


if __name__ == "__main__":
    sys.exit(_main(*sys.argv[1:]))
